import { getStagedDiff, getFullDiff, getPRDiff, getPRLog, abbreviateDiff, getCurrentBranch, isGitAvailable } from './commands.js';
import type { AIProvider, AIProviderConfig } from '../ai/provider.js';
import { getDefaultModel, resolveModel } from '../ai/registry.js';

export interface MessageOptions {
  provider?: AIProvider;
  providerConfig?: AIProviderConfig;
  detail?: 'brief' | 'normal' | 'detailed';
}

function getDefaultProvider(): { provider: AIProvider; config: AIProviderConfig } {
  const defaultModel = getDefaultModel();
  const resolved = resolveModel(defaultModel.model);
  const provider = resolved.entry.provider;
  const config = resolved.entry.getConfig
    ? resolved.entry.getConfig(resolved.model)
    : { model: resolved.model, temperature: 0.3, maxTokens: 512 };
  return { provider, config };
}

const COMMIT_PROMPT = `You are a commit message generator. Analyze the provided git diff and generate a concise, conventional commit message.

Format: <type>(<scope>): <description>

Types: feat, fix, refactor, test, docs, style, chore, perf, ci
Scope is optional.

Rules:
- First line: max 72 characters
- If needed, follow with a blank line and bullet points for details
- Focus on WHAT and WHY, not HOW
- Use imperative mood

Respond with ONLY the commit message, no explanations.`;

const PR_SUMMARY_PROMPT = `You are a PR summary generator. Analyze the provided branch diff and commit log, then generate a comprehensive pull request summary.

Format:
## Summary
<brief overview of changes>

## Changes
- <bullet point per logical change>

## Motivation
<why these changes were made>

## Testing
<suggested testing approach>

Keep it concise but informative. Focus on the impact of changes.`;

export async function generateCommitMessage(options?: MessageOptions): Promise<string> {
  if (!isGitAvailable()) return 'git not available';

  let diff = getStagedDiff();
  if (!diff) diff = getFullDiff();
  if (!diff) return 'No changes detected';

  const { provider, config } = options?.provider
    ? { provider: options.provider, config: options.providerConfig || { model: 'default', temperature: 0.3, maxTokens: 512 } }
    : getDefaultProvider();

  const truncatedDiff = abbreviateDiff(diff, 150);
  const messages = [
    { role: 'system' as const, content: COMMIT_PROMPT },
    { role: 'user' as const, content: `Git diff:\n\n${truncatedDiff}` },
  ];

  try {
    return await provider.chat(messages, { ...config, temperature: 0.3, maxTokens: 512 });
  } catch {
    return fallbackCommitMessage(diff);
  }
}

export async function generatePRSummary(baseBranch?: string, options?: MessageOptions): Promise<string> {
  if (!isGitAvailable()) return 'git not available';

  const branch = getCurrentBranch();
  const base = baseBranch || 'main';
  const diff = getPRDiff(base);
  const log = getPRLog(base);

  if (!diff && log.length === 0) return `No changes between ${base} and ${branch}`;

  const { provider, config } = options?.provider
    ? { provider: options.provider, config: options.providerConfig || { model: 'default', temperature: 0.3, maxTokens: 1024 } }
    : getDefaultProvider();

  const truncatedDiff = abbreviateDiff(diff, 200);
  const commitLog = log.map((e) => `  - ${e.message}`).join('\n');

  const messages = [
    { role: 'system' as const, content: PR_SUMMARY_PROMPT },
    {
      role: 'user' as const,
      content: `Branch: ${branch} → ${base}\n\nCommits:\n${commitLog}\n\nDiff:\n${truncatedDiff}`,
    },
  ];

  try {
    return await provider.chat(messages, { ...config, temperature: 0.3, maxTokens: 1024 });
  } catch {
    return fallbackPRSummary(branch, base, log);
  }
}

function fallbackCommitMessage(diff: string): string {
  const lines = diff.split('\n');
  const added = lines.filter((l) => l.startsWith('+') && !l.startsWith('+++')).length;
  const removed = lines.filter((l) => l.startsWith('-') && !l.startsWith('---')).length;
  const filesChanged = new Set(
    lines.filter((l) => l.startsWith('diff --git')).map((l) => l.split(' b/')[1]),
  ).size;

  const type = removed > added ? 'fix' : 'refactor';
  return `${type}: update ${filesChanged} file${filesChanged > 1 ? 's' : ''} (+${added} -${removed})`;
}

function fallbackPRSummary(branch: string, base: string, log: import('./commands.js').GitLogEntry[]): string {
  return `## Summary
Changes on branch \`${branch}\` relative to \`${base}\`.

## Changes
${log.map((e) => `- ${e.message}`).join('\n')}

## Motivation
Automated summary generated by LoveCode AI.`;
}
